//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBRouCity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int idPago { get; set; }
        public Nullable<decimal> importe { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipoPasarela { get; set; }
        public int idViaje { get; set; }
        public int idUsuario { get; set; }
        public Nullable<bool> Anulado { get; set; }
        public string motivoAnulado { get; set; }
    
        public virtual Viaje Viaje { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
