//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBRouCity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viaje()
        {
            this.Pago = new HashSet<Pago>();
            this.Valoracion = new HashSet<Valoracion>();
            this.ViajePasajero = new HashSet<ViajePasajero>();
        }
    
        public int idViaje { get; set; }
        public int idUChofer { get; set; }
        public decimal latOrigen { get; set; }
        public decimal longOrigen { get; set; }
        public decimal latDestino { get; set; }
        public decimal longDestino { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal precio { get; set; }
        public System.TimeSpan hora { get; set; }
        public string cocheDescripcion { get; set; }
        public int asientosDisponibles { get; set; }
        public Nullable<short> calificacion { get; set; }
        public string comentario { get; set; }
        public Nullable<short> cantParada { get; set; }
        public Nullable<decimal> tiempoParada { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valoracion> Valoracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ViajePasajero> ViajePasajero { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
